name: Test Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Installer Rust
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build and Install QBE
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git
          git config --global http.allowProtocols "http,https,file,ftp"
          git config --global http.curloptResolve ""
          git clone https://c9x.me/git/qbe.git /tmp/qbe
          cd /tmp/qbe
          make
          sudo make install
          qbe -v

      - name: Cargo Check
        run: cargo check --all-targets

      - name: Build & Test Standard Library
        run: cargo run -- std/std.mrw